apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  creationTimestamp: null
  name: istio-egressgateway-istiobroker
spec:
  selector:
    istio: egressgateway
  servers:
  - hosts:
    - istiobroker-egress.istio-system.svc.cluster.local
    port:
      name: http-port-80
      number: 80
      protocol: HTTP