apiVersion: v1
kind: Service
metadata:
  name: {{ template "istio-broker-proxy.fullname" . }}
  labels:
    app: {{ template "istio-broker-proxy.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service_port }}
    targetPort: {{ .Values.global.container_port }}
    name: http
  selector:
    app:  {{ template "istio-broker-proxy.fullname" . }}