# Default values for istio-broker-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository:
  digest:
  tag: latest
  pullPolicy: Always
  pullsecret: image-pull-secret

config:
  forward_url: http://istiobroker-egress.istio-system.svc.cluster.local:80
  container_port: 8888
  consumer_id: 
  network_profile: urn:com.sap.istio:public
  service_port: 9999
  service_prefix: istio-



broker:
  enabled: true
  url: istiobroker.catalog.svc.cluster.local
  user:
  password:

istio-config:
  enabled: false
  pinger_port: 9000

global:
  destination:
    landscape_domain: cf.landscape.com
    port: 9000