# Default values for istio-broker-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
maxUnavailable: 0
maxSurge: 2

image:
  repository: gcr.io/peripli
  digest:
  tag: latest
  pullPolicy: Always
  pullsecret: image-pull-secret

config:
  forward_url:
  consumer_id:
  network_profile:
  service_prefix: istio-

pinger:
  port: 9000

standalone:
  enabled: false
  broker:
    url: istiobroker.catalog.svc.cluster.local
    user:
    password:

global:
  service_port: 9999
  container_port: 8888
  destination:
    landscape_domain: cf.landscape.com
    port: 9000

