apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "istio-broker-proxy.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "istio-broker-proxy.fullname" . }}
    spec:
      {{- if .Values.image.pullsecret }}
      imagePullSecrets:
      - name: {{.Values.image.pullsecret}}
      {{- end }}
      containers:
      {{- if .Values.image.digest }}
      - image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
      {{- else}}
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      {{- end}}
        name: istiobroker
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.config.container_port }}
        args:
        - "--port"
        - "{{ .Values.config.container_port }}"
        - "--forwardUrl"
        - "{{ .Values.config.forward_url }}"
        - "--consumerId"
        - "{{ .Values.config.consumer_id }}"
        - "--serviceNamePrefix"
        - "{{ .Values.config.service_prefix }}"
        - "--networkProfile"
        - "{{ .Values.config.network_profile }}"
        