apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "istio-broker-proxy.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: {{ template "istio-broker-proxy.fullname" . }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: {{ template "istio-broker-proxy.fullname" . }}
              topologyKey: kubernetes.io/hostname
      {{- if .Values.image.pullsecret }}
      imagePullSecrets:
      - name: {{.Values.image.pullsecret}}
      {{- end }}
      containers:
      {{- if .Values.image.digest }}
      - image: "{{ required "A valid image.repository entry required!" .Values.image.repository }}/istio-broker@{{ .Values.image.digest }}"
      {{- else}}
      - image: "{{ required "A valid image.repository entry required!" .Values.image.repository }}/istio-broker:{{ .Values.image.tag }}"
      {{- end}}
        name: istiobroker
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.global.container_port }}
          name: http-port
        readinessProbe:
          httpGet:
            path: /health
            port: http-port
        livenessProbe:
          httpGet:
            path: /health
            port: http-port
        args:
        - "--port"
        - "{{ .Values.global.container_port }}"
        - "--forwardUrl"
        - "{{ required "A valid config.forward_url entry required!" .Values.config.forward_url }}"
        - "--consumerId"
        - "{{ required "A valid config.consumer_id entry required!" .Values.config.consumer_id }}"
        - "--serviceNamePrefix"
        - "{{ .Values.config.service_prefix }}"
        - "--networkProfile"
        - "{{ required "A valid config.network_profile entry required!" .Values.config.network_profile }}"
        