apiVersion: batch/v1
kind: Job
metadata:
  name: pinger-config
spec:
  template:
    spec:
      containers:
        - name: pinger-config
          image: gcr.io/peripli/client
          command: [ "/app/client","-client","-port","5555","-service","pinger","-virtual-service","pinger","-system-domain", "istio.{{.Values.global.destination.landscape_domain}}" ]
      restartPolicy: Never
  backoffLimit: 4
