apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  creationTimestamp: null
  name: istiobroker-serviceentry
spec:
  hosts:
  - istio-broker.istio.{{.Values.global.destination.landscape_domain}}
  ports:
  - name: tcp-port-{{.Values.global.destination.port}}
    number: {{.Values.global.destination.port}}
    protocol: TLS
  resolution: DNS